name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 
      - 'chore'
      - 'ci'
      - 'docs'

exclude-labels:
 - 'skip'

autolabeler:
  - label: 'bug'
    title:
      - '/.*\[fix\].*/'
  - label: 'patch'
    title:
      - '/.*\[fix\].*/'
  - label: 'enhancement'
    title:
      - '/.*\[feat\].*/'
  - label: 'minor'
    title:
      - '/.*\[feat\].*/'
  - label: 'skip'
    title:
      - '/.*\[skip\].*/'
  - label: 'major'
    title:
      - '/.*\[breaking\].*/'

replacers:
  - search: '/\[feat\]/g'
    replace: ''
  - search: '/\[fix\]/g'
    replace: ''
  - search: '/\[skip\]/g'
    replace: ''
  - search: '/\[breaking\]/g'
    replace: ''

template: |
  # What's Changed
  $CHANGES
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.