name: On Release - Publish

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: "tag"
        required: true

jobs:
  publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 35

    steps:
      - name: Set tag
        if: ${{ github.event.release }}
        run: echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Set tag
        if: ${{ github.event.inputs.tag }}
        run: echo "RELEASE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true

      - name: Build
        run: cargo build --all-targets --release 

      - name: Test
        run: cargo test --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/firepilot
          asset_name: firepilot-x64-unknown-linux-gnu
          overwrite: true